repos:
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
-   repo: local
    hooks:
    - id: flake8
      name: flake8
      entry: flake8
      language: python
      types: [python]
      exclude: (?x)^(django_admin/.* |etl/src/queries/.* | filmwork_service/.*/__init__.py | file_service/.*/__init__.py | auth_service/.*/__init__.py | auth_service/src/migrations/.* | ucg_service/src/app/.*/__init__.py | ucg_service/src/pywsgi.py | ucg_service/src/.*/__init__.py | notification_service/src/core/grpc/.* | notification_service/src/migrations/.* | notification_consumer/src/grpc/models/.* | notification_consumer/src/grpc/services/.* | url_shortener_service/src/migrations/.*  )$
-   repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
    - id: isort
      args: ["--profile", "black"]