version: '3'
x-filebeat-common:
  &filebeat-common
  build:
    context: ./logging/deploy/filebeat
  depends_on:
    - elastic-elk
    - logstash
    - kibana-elk
    - proxy

services:
  django-admin:
    build: django_admin
    image: app-django-admin:run
    depends_on:
      - postgres
    env_file:
      - envs/.env.django
    expose:
      - "8000"
    restart: unless-stopped
    volumes:
      - static:/opt/app/static
      - django-admin-logs:/opt/logs # Для ELK+Filebeat

  auth-api:
    build: auth_service
    image: app-auth-api:run
    depends_on:
      - redis-auth
      - postgres-auth
    env_file:
      - envs/.env.api.auth
    restart: unless-stopped
    volumes:
      - auth-api-logs:/opt/logs # Для ELK+Filebeat

  film-api:
    build: filmwork_service
    image: app-film-api:run
    depends_on:
      - redis-films
      - elastic
    env_file:
      - envs/.env.api.films
    restart: unless-stopped
    volumes:
      - film-api-logs:/opt/logs # Для ELK+Filebeat

  file-api:
    build: file_service
    image: app-file-api:run
    depends_on:
      - redis
      - postgres
      - minio
    env_file:
      - envs/.env.files
    restart: unless-stopped
    volumes:
      - file-api-logs:/opt/logs # Для ELK+Filebeat

  redis-films:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - films-cache:/data

  redis-auth:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - auth-cache:/data


  proxy:
    build: ./nginx/
    image: app-nginx-proxy:latest
    volumes:
      - static:/data/static/:ro
      - nginx-logs:/var/log/nginx/ # Логирование в файл для ELK+Filebeat
    depends_on:
      - django-admin
    ports:
      - "81:80"

  postgres:
    build: postgres/
    image: app-postgres
    env_file:
      - envs/.env.database
    volumes:
      - postgres-data:/var/lib/postgresql/data

  postgres-auth:
    image: postgres:latest
    env_file:
      - envs/.env.database.auth
    volumes:
      - auth-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis-data:/data

  elastic:
    build: elastic/
    image: app-elasticsearch
    restart: unless-stopped
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  etl:
    build: ./etl
    image: app-etl-process:run
    env_file:
      - envs/.env.etl
    depends_on:
      - postgres
      - django-admin
      - proxy
      - redis
      - elastic
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    env_file:
      - ./envs/.env.s3
    command: server --console-address ":9001" /data


  elastic-logs:
    build: elastic/
    image: app-elasticsearch
    restart: unless-stopped
    volumes:
      - elastic-logs:/usr/share/elasticsearch/data
    ports:
      - "9201:9200"


  jaeger-collector:
    image: jaegertracing/jaeger-collector:latest
    environment:
      SPAN_STORAGE_TYPE: elasticsearch
      ES_SERVER_URLS: http://elastic-logs:9200
    ports:
      - "14250:14250"
      - "14267:14267"
      - "14268:14268"
      - "9411:9411"
    depends_on:
      - elastic
    restart: unless-stopped

  jaeger-query:
    image: jaegertracing/jaeger-query:latest
    ports:
      - "16686:16686"
      - "16687:16687"
    environment:
      SPAN_STORAGE_TYPE: elasticsearch
      ES_SERVER_URLS: http://elastic-logs:9200
    restart: unless-stopped

  event-api:
    build: ./ucg_service
    image: ucg_service:prod
    env_file:
      - envs/.env.api.ucg
    depends_on:
      - auth-api
    ports:
      - "5001:5001"
    restart: unless-stopped
    volumes:
      - event-api-logs:/opt/logs # Для ELK+Filebeat

  event-etl:
    build: ucg_etl
    image: ucg_etl:prod
    env_file:
      - envs/.env.etl.ucg
    restart: unless-stopped

  logstash:
    image: logstash:8.10.2
    depends_on:
      - elastic-elk
    environment:
      XPACK_MONITORING_ENABLED: "false"
      ES_HOST: "elastic-elk:9200"
    volumes:
      - ./logging/deploy/logstash.conf:/config/logstash.conf:ro
      # - /tmp/logs/nginx/:/var/log/nginx/:ro
    command: logstash -f /config/logstash.conf 

  elastic-elk:
    image: elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms265m -Xmx265m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic-elk-data:/usr/share/elasticsearch/data

  kibana-elk:
    image: kibana:8.10.2
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic-elk:9200
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    depends_on:
      - elastic-elk

  filebeat-nginx:
    <<: *filebeat-common
    environment:
      - SERVICE_NAME=nginx
    depends_on:
      - proxy
    volumes:
      - nginx-logs:/var/app/log:ro # Логирование в файл для ELK+Filebeat

  filebeat-django-admin:
    <<: *filebeat-common
    environment:
      - SERVICE_NAME=django-admin
    depends_on:
      - django-admin
    volumes:
      - django-admin-logs:/var/app/log:ro

  filebeat-auth-api:
    <<: *filebeat-common
    environment:
      - SERVICE_NAME=auth-api
    depends_on:
      - auth-api
    volumes:
      - auth-api-logs:/var/app/log:ro

  filebeat-film-api:
    <<: *filebeat-common
    environment:
      - SERVICE_NAME=film-api
    depends_on:
      - film-api
    volumes:
      - film-api-logs:/var/app/log:ro

  filebeat-file-api:
    <<: *filebeat-common
    environment:
      - SERVICE_NAME=file-api
    depends_on:
      - file-api
    volumes:
      - file-api-logs:/var/app/log:ro

  filebeat-event-api:
    <<: *filebeat-common
    environment:
      - SERVICE_NAME=event-api
    depends_on:
      - event-api
    volumes:
      - event-api-logs:/var/app/log:ro

volumes:
  static:
  auth-data:
  postgres-data:
  redis-data:
  elastic-data:
  films-cache:
  pg-cache:
  auth-cache:
  minio_storage:
  elastic-logs:
  elastic-elk-data:
  # Filebeat volumes
  nginx-logs:
  django-admin-logs:
  auth-api-logs:
  film-api-logs:
  file-api-logs:
  event-api-logs:

