# Generated by Django 5.0.4 on 2024-05-08 13:58

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import tinymce.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=255, unique=True, verbose_name='login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'content"."users',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('body', models.TextField(blank=True, verbose_name='body')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'content"."messages',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('layout', tinymce.models.HTMLField(verbose_name='layout')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'db_table': 'content"."templates',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='CREATED', editable=False, max_length=10, verbose_name='status')),
                ('users_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), size=None, verbose_name='users_ids')),
                ('is_instant', models.BooleanField(default=True, verbose_name='is_instant')),
                ('schedule_at', models.DateTimeField(default=django.utils.timezone.now, help_text="Укажите в случае, если вы сняли галку в пункте 'Мгновенная отправка' и хотите отправить уведомление отложенно", verbose_name='schedule_at')),
                ('additional_info', models.JSONField(blank=True, default={}, help_text="Любая дополнительная информация для шаблона в формате ключ-значение, например {'user_from_id': 'c9212aef-0959-4b94-aee2-5cf9c9ae6bd1'}", null=True, verbose_name='additional_info')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='notify.message', verbose_name='Message')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='notify.template', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'content"."notifications',
            },
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('template', 'message', 'users_ids', 'schedule_at'), name='unique_notification_for_users_ids'),
        ),
    ]
