apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
type: Opaque
data:
  admin-user: YWRtaW4=  # admin
  admin-password: cGFzc3dvcmQ=  # password

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alert-template
  namespace: monitoring
data:
  __default__.tmpl: |
    {{ define "__default__" }}
    {{ template "__content" . }}
    {{ end }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-admin-secret
                  key: admin-user
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-admin-secret
                  key: admin-password
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: grafana-alert-templates
              mountPath: /etc/grafana/alerting/__default__.tmpl
              subPath: __default__.tmpl
      volumes:
        - name: grafana-storage
          emptyDir: { }
        - name: grafana-alert-templates
          configMap:
            name: grafana-alert-template

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: grafana