apiVersion: v1
kind: Service
metadata:
  name: django-notification-service
spec:
  type: NodePort
  selector:
    app: django-notification-service
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-notification-service
spec:
  selector: 
    matchLabels:
      app: django-notification-service
  replicas: 1
  template:
    metadata:
      labels:
        app: django-notification-service
    spec:
      containers:
        - name: django-notification-service
          image: notification-admin:latest
          envFrom:
            - secretRef:
                name: notify-admin
          imagePullPolicy: Never
          resources:
            limits: 
              memory: "400Mi"
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: "/"
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 2
            failureThreshold: 5

---

apiVersion: batch/v1
kind: Job
metadata:
  name: django-notifications-migrations
spec:
  backoffLimit: 2
  activeDeadlineSeconds: 100
  template:
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nc -z -v -w30 $DB_HOST $DB_PORT; do echo "Waiting for database..."; sleep 5; done']
          envFrom:
            - secretRef:
                name: notify-admin
      containers:
      - name: django-notification-service
        image: notification-admin:latest
        command: ["/bin/sh", "-c", "python ./manage.py migrate" ]
        imagePullPolicy: Never
        envFrom:
          - secretRef:
              name: notify-admin
      restartPolicy: Never


---
apiVersion: v1
data:
  ALLOWED_HOSTS: Kg==
  AUTH_API_LOGIN_URL: aHR0cDovL2F1dGgtc2VydmljZTo4MDAwL2FwaS92MS9hY2NvdW50cy9sb2dpbg==
  AUTH_API_PROFILE_URL: aHR0cDovL2F1dGgtc2VydmljZTo4MDAwL2FwaS92MS91c2Vycy9wcm9maWxl
  DB_HOST: ODQuMjAxLjE2MC4yNA==
  DB_NAME: bm90aWZ5X2RhdGFiYXNl
  DB_PASSWORD: MTIzcXdl
  DB_PORT: NTQzNA==
  DB_USER: YXBw
  DEBUG: VHJ1ZQ==
  DJANGO_SUPERUSER_EMAIL: YWRtaW5AbWFpbC5ydQ==
  DJANGO_SUPERUSER_PASSWORD: cXdlcnR5
  DJANGO_SUPERUSER_USERNAME: YWRtaW4=
  MINIO_STORAGE_ACCESS_KEY: MzVJemtkVGFZd0tUYU9xWXdvcUc=
  MINIO_STORAGE_AUTO_CREATE_MEDIA_BUCKET: VHJ1ZQ==
  MINIO_STORAGE_AUTO_CREATE_STATIC_BUCKET: VHJ1ZQ==
  MINIO_STORAGE_ENDPOINT: ODQuMjAxLjE2MC4yNDo5MDAw
  MINIO_STORAGE_MEDIA_BACKUP_BUCKET: J1JlY3ljbGUgQmluJw==
  MINIO_STORAGE_MEDIA_BACKUP_FORMAT: JWMv
  MINIO_STORAGE_MEDIA_BUCKET_NAME: bm90aWZpY2F0aW9uLW1lZGlh
  MINIO_STORAGE_SECRET_KEY: SkVlYnBCdTdMOXlqZjU1emo2WGVmTGxuYnpqV24xcGRWeVpyV3VoaQ==
  MINIO_STORAGE_STATIC_BUCKET_NAME: bm90aWZpY2F0aW9uLXN0YXRpYw==
  MINIO_STORAGE_USE_HTTPS: RmFsc2U=
  NOTIFICATION_SERVICE_GRPC: bm90aWZpY2F0aW9uLXNlcnZpY2U6NTAwNTE=
  S3_STORAGE_BUCKET_NAME: ZmlsZXM=
  SECRET_KEY: ZXhhbXBsZQ==
kind: Secret
metadata:
  creationTimestamp: "2024-06-28T22:00:46Z"
  name: notify-admin
  namespace: default
  resourceVersion: "966995"
  uid: b5cc431a-8ac0-4564-b612-10538fd0d9be
type: Opaque