# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ucg.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\tucg.proto\x1a\x1bgoogle/protobuf/empty.proto">\n\x1a\x43ommentNotificationRequest\x12\x0f\n\x07\x66ilm_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t"H\n OldBookmarkedNotificationRequest\x12\x13\n\x0b\x62ookmark_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t2\xc8\x01\n\x16UcgNotificationService\x12P\n\x17SendCommentNotification\x12\x1b.CommentNotificationRequest\x1a\x16.google.protobuf.Empty"\x00\x12\\\n\x1dSendOldBookmarkedNotification\x12!.OldBookmarkedNotificationRequest\x1a\x16.google.protobuf.Empty"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "ucg_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_COMMENTNOTIFICATIONREQUEST"]._serialized_start = 42
    _globals["_COMMENTNOTIFICATIONREQUEST"]._serialized_end = 104
    _globals["_OLDBOOKMARKEDNOTIFICATIONREQUEST"]._serialized_start = 106
    _globals["_OLDBOOKMARKEDNOTIFICATIONREQUEST"]._serialized_end = 178
    _globals["_UCGNOTIFICATIONSERVICE"]._serialized_start = 181
    _globals["_UCGNOTIFICATIONSERVICE"]._serialized_end = 381
# @@protoc_insertion_point(module_scope)
