# Generated by Django 3.2 on 2023-12-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filmwork",
            name="file",
            field=models.FileField(null=True, upload_to="uploads/"),
        ),
    ]
