# Generated by Django 5.0 on 2023-12-18 12:22

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_filmwork_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filmwork",
            name="file",
            field=models.FileField(
                null=True, storage=storages.backends.s3.S3Storage(), upload_to=""
            ),
        ),
    ]
