# Generated by Django 5.0 on 2023-12-18 12:26

import movies.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_alter_filmwork_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filmwork",
            name="file",
            field=models.FileField(
                null=True, storage=movies.storage.CustomStorage(), upload_to=""
            ),
        ),
    ]
