# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.grpc.models import status_pb2 as status__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\nfile.proto\x1a\x0cstatus.proto"2\n\x1f\x46ilmUploadedNotificationRequest\x12\x0f\n\x07\x66ilm_id\x18\x01 \x01(\t2W\n\x10\x46ilmNotification\x12\x43\n\x14SendFilmNotification\x12 .FilmUploadedNotificationRequest\x1a\x07.Status"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "file_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_FILMUPLOADEDNOTIFICATIONREQUEST"]._serialized_start = 28
    _globals["_FILMUPLOADEDNOTIFICATIONREQUEST"]._serialized_end = 78
    _globals["_FILMNOTIFICATION"]._serialized_start = 80
    _globals["_FILMNOTIFICATION"]._serialized_end = 167
# @@protoc_insertion_point(module_scope)
