"""Initial tables

Revision ID: b2fd8dd72865
Revises: 
Create Date: 2024-05-08 19:55:03.966450

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b2fd8dd72865"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "system_notifications",
        sa.Column(
            "content_type",
            sa.Enum(
                "user_registered",
                "user_activated",
                "user_deactivated",
                "film_published",
                "bookmark_expired",
                name="contenttype",
            ),
            nullable=False,
        ),
        sa.Column("content_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "started",
                "in_progress",
                "completed",
                "cancelled",
                "sceduled",
                name="notificationstatus",
            ),
            nullable=False,
        ),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.Column("last_notification_send", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_notifications",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "notification_type",
            sa.Enum(
                "fast_notification",
                "delayed_notification",
                "scheduled_notification",
                name="notificationtype",
            ),
            nullable=False,
        ),
        sa.Column(
            "notification_channel_type",
            sa.Enum("email", "sms", "push", name="notificationchanneltype"),
            nullable=False,
        ),
        sa.Column("notification_id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("subject", sa.String(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "started",
                "in_progress",
                "completed",
                "cancelled",
                "sceduled",
                name="notificationstatus",
            ),
            nullable=False,
        ),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.Column("last_notification_send", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_notifications")
    op.drop_table("system_notifications")
    # ### end Alembic commands ###
