import os 

DEFAULT_FILE_STORAGE = "minio_storage.storage.MinioMediaStorage"
STATICFILES_STORAGE = "minio_storage.storage.MinioStaticStorage"
MINIO_STORAGE_ENDPOINT = os.environ.get("MINIO_STORAGE_ENDPOINT")
MINIO_STORAGE_ACCESS_KEY = os.environ.get("MINIO_STORAGE_ACCESS_KEY")
MINIO_STORAGE_SECRET_KEY = os.environ.get("MINIO_STORAGE_SECRET_KEY")
MINIO_STORAGE_USE_HTTPS = os.environ.get("MINIO_STORAGE_USE_HTTPS", "False") == "True"
MINIO_STORAGE_MEDIA_OBJECT_METADATA = {"Cache-Control": "max-age=1000"}
MINIO_STORAGE_MEDIA_BUCKET_NAME = os.environ.get("MINIO_STORAGE_MEDIA_BUCKET_NAME")
MINIO_STORAGE_MEDIA_BACKUP_BUCKET = os.environ.get("MINIO_STORAGE_MEDIA_BACKUP_BUCKET")
MINIO_STORAGE_MEDIA_BACKUP_FORMAT = os.environ.get("MINIO_STORAGE_MEDIA_BACKUP_FORMAT")
MINIO_STORAGE_AUTO_CREATE_MEDIA_BUCKET = os.environ.get("MINIO_STORAGE_AUTO_CREATE_MEDIA_BUCKET", "True") == "True"
MINIO_STORAGE_STATIC_BUCKET_NAME = os.environ.get("MINIO_STORAGE_STATIC_BUCKET_NAME")
MINIO_STORAGE_AUTO_CREATE_STATIC_BUCKET = os.environ.get("MINIO_STORAGE_AUTO_CREATE_STATIC_BUCKET", "True") == "True"